varReference:
- path: metadata/name
  kind: Client
  apiVersion: dex.betssongroup.com/v1
- path: spec/redirectURIs
  kind: Client
  apiVersion: dex.betssongroup.com/v1
- path: spec/secret
  kind: Client
  apiVersion: dex.betssongroup.com/v1